# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b8dcee88ac2df81028f9c783c08930b496a2ac4fe7d4dff8d84cebfe3dee8c1d4257e985001107b1bcc20a630a061c19eee5cd01660adfb533a3754d8328913

test:
  secret_key_base: 46dc13656b02ebb0cc296fc2c95531be6f88efe241ee571476085c0a2cd68dad38284f9c3cebdafbd7ad1b43836cc2685974485376b2b59012b94a9a1aa7da67

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
